name: Build Images and push to ghcr.io

on:
  push:
    branches:
      - master

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/haocen/openvpn-socks:latest